### ISSUE TITLE
ENH: Missing test for Stairs.logical_xor for Stairs over float domain

### ISSUE THREAD

**Issue by venaturum** [staircase-dev/staircase#105]
#### Describe the solution you'd like

Belongs here:

https://github.com/staircase-dev/staircase/blob/00da1209eec21d3ea11f0f18f538637d2bae5ecf/tests/test_floats/test_floats_logical.py

Docs:
https://www.staircase.dev/en/latest/reference/api/staircase.Stairs.logical_xor.html

Is tested with a Stairs and scalar operands but needs to be tested with two Stairs operands.

**Comment by amagee** [comment]
take
