### ISSUE TITLE
ENH: add mypy to environment

### ISSUE THREAD

**Issue by venaturum** [staircase-dev/staircase#155]
Create `mypy.ini` in top level folder

Eliminate errors when running `mypy -m staircase`

**Comment by PabloRuizCuevas** [comment]
As far as I know we can put the configuration of mypy in the poetry.toml, I can put a basic configuration.

**Comment by PabloRuizCuevas** [comment]
Already in #154

**Comment by venaturum** [comment]
Thanks Pablo!
