### ISSUE TITLE
BUG: staircase.make_test_data fails with numpy < 1.17

### ISSUE THREAD

**Issue by venaturum** [staircase-dev/staircase#80]
- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of staircase.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
>>> import staircase as sc
>>> sc.make_test_data()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rclement\Documents\temp11\.venv\lib\site-packages\staircase\test_data.py", line 56, in make_test_data
    return _make_test_data(dates=dates, positive_only=positive_only, seed=seed)
  File "C:\Users\rclement\Documents\temp11\.venv\lib\site-packages\staircase\test_data.py", line 71, in _make_test_data
    rng = np.random.default_rng()
AttributeError: module 'numpy.random' has no attribute 'default_rng'

```

#### Dependency Versions``

<details>

staircase 2.0.0
pandas 1.0.0
numpy 1.16.0

</details>

**Comment by PabloRuizCuevas** [comment]
I would consider raising the numpy minimum version requirements to 1.19 for python 3.6 onwards.

[numpy news](https://numpy.org/news/)
`Jun 20, 2020 – NumPy 1.19.0 is now available. This is the first release without Python 2 support, hence it was a “clean-up release”. The minimum supported Python version is now Python 3.6. An important new feature is that the random number generation infrastructure that was introduced in NumPy 1.17.0 is now accessible from Cython.`

**Comment by venaturum** [comment]
Hi Pablo, thanks for taking an interest in staircase!

Support for Python 3.6 will be dropped in the next release of staircase anyway, but I think its worth discussing a couple of things.

Python 3.6 was released late 2016, when numpy 1.11.2 was the latest release, and numpy 1.19 was released 3.5 years after this.  Because staircase is a library we want the dependencies to be as accommodating as possible.  This is made even more important given the complete mess that dependency resolution and packaging in Python is (and continues to be).  

I agree that it in general it would be preferable for users to use later versions of numpy, for many reasons, but I don't think it is our place to enforce that on them if the staircase code can work with earlier versions.  It seems the only instance of an earlier numpy version causing a problem for us is this `make_test_data` function, which is not exactly a huge problem, and could be solved with a workaround which tests for numpy version before executing code.

Back to dependency resolution... let's say we had given numpy a lower bound of 1.19 from the start.  It could be possible that a user has another package in their environment which requires numpy < 1.19, and the environment would not be resolvable if including staircase. Or perhaps there is a user who has a numpy version < 1.19 and they wish to introduce staircase into their environment without changing any of their existing dependencies - they would not be able to and there doesn't seem to be a good reason to prevent them from doing so since the code should still work.

Since published versions of staircase exist which are compatible with numpy < 1.19, publishing a new version which restricts numpy >= 1.19 will result in two cases for environment resolution:

i) The user has no constraints in their environment which force numpy < 1.19 and their dependency resolver (eg pip, poetry, conda etc) will generally choose the latest version of numpy it can (which will be >= 1.19 but perhaps not the very latest depending on other constraints).  In this case the dependency resolver is free to choose the newly published staircase package where numpy is required to be above 1.19

ii) The user has a constraint that numpy < 1.19 - either directly introduced by themselves, or by a dependency (or a dependency of a dependency etc).  In this case the dependency resolver will just choose an earlier version of staircase that is compatible with the earlier numpy version.  The user will have been prevented from using the later version of staircase (again, for no concrete reason).

It's hard to see what benefit introducing the numpy 1.19 restriction would have, but happy to keep the conversation going.  I'm generally flying solo on this project so it's good to have other opinions.

**Comment by PabloRuizCuevas** [comment]
Thanks for the explanation, I'm aware of the pros and cons and normally I would still say that the inconveniences are greater than the benefits, but as you stated:

_It seems the only instance of an earlier numpy version causing a problem for us is this make_test_data function, which is not exactly a huge problem_

So I agree with you that being only one case maybe the best idea just to patch it. [some link for the possible implementation for consulting in the near future](https://stackoverflow.com/questions/62077194/can%C2%B4t-import-qiskit-attribute-error-in-numpy-numpy-random-has-no-attribute)

**Comment by venaturum** [comment]
fantastic :)
