### ISSUE TITLE
ENH: Allow Stairs.fillna to take a Stairs parameter

### ISSUE THREAD

**Issue by venaturum** [staircase-dev/staircase#82]
#### Is your feature request related to a problem?

We want the value parameter in Stairs.fillna to be able to take a staircase.Stairs parameter 

current definition https://github.com/staircase-dev/staircase/blob/cb0265d1b182ad3a8452f544c197ce54aef6feea/staircase/core/ops/masking.py#L160

docstring https://github.com/staircase-dev/staircase/blob/cb0265d1b182ad3a8452f544c197ce54aef6feea/staircase/core/ops/docstrings.py#L459

#### Describe the solution you'd like

See https://www.staircase.dev/en/latest/user_guide/cookbook.html#fill-undefined-intervals-of-one-step-function-with-another for an implementation

**Comment by ChristopherShort** [comment]
take

**Comment by ChristopherShort** [comment]
Hi - whilst implementing the suggested approach is straightforward - it has the side effect of leaving zeros in the mutated SC object if the replacing SC also has nans that overlap.

I would expect this case to leave those nans as nans, replacing only those nans where the replacing SC has values

The logic for this is straightforward - but I'm still to fully understand the data structure to implement it.  A few attempts aren't yet working.

aka - I'm still plugging away

**Comment by venaturum** [comment]
Hi @ChristopherShort, good catch!

Will certainly have to be one of the tests!

I have a solution which builds on the original one liner, without having to delve into the internals of staircase.  Don't want to ruin it for you if you're enjoying figuring out so I'm happy to either give you the fix, give you a hint, or neither.  It's up to you.
