### ISSUE TITLE
ENH: raise error if operands of binary operations do not have same "closed" value

### ISSUE THREAD

**Issue by venaturum** [staircase-dev/staircase#96]
#### Describe the solution you'd like

Stairs instances have a "closed" property which can be "left" or "right" indicates if they are left-closed, right-open  or right-closed left-open.

When performing binary operations with two Stairs objects, like addition, &, >= etc it is important that both operands have the same value of closed, and an error should be raised if not.

It would be great to have this functionality implemented as a function decorator, which knows to compare *self* and *other* parameters which appear in these binary operator methods.

**Comment by amagee** [comment]
take

**Comment by venaturum** [comment]
There is a function [_sanitise_binary_operands](https://github.com/staircase-dev/staircase/blob/8356e53b3cfa04d9ca5fd0228b6d0091d492793b/staircase/util/__init__.py#L16) which could come in handy.  It is called each time a binary operation is applied, to convert any numerical operands to Stairs.

At the moment when it converts from numerical to Stairs, the default value for "closed" is used ("left").  We may need to set the closed parameter accordingly in this function, and/or make sure the checks pass if Stairs.number_of_steps == 0.

I.e. 
```
sc.Stairs(closed="left") + 1

sc.Stairs(closed="right") + 1

1 + sc.Stairs(closed="left")

1 + sc.Stairs(closed="right")
```
would all need to work without errors.

**Comment by venaturum** [comment]
I've suggested it would be nice to have the functionality as a decorator, (and to be honest _sanitise_binary_operands would be nice to have as a decorator), but first step is probably to iron out any wrinkles in the logic, and have it pass tests  before we worry about transforming it into a decorator.

I might write some tests for it if that helps?

**Comment by venaturum** [comment]
@amagee actually, I noticed you're a few steps ahead :D I'll take a look at your PR
