### ISSUE TITLE
DOC: Typo in "How can I compare my step function"

### ISSUE THREAD

**Issue by venaturum** [staircase-dev/staircase#99]
#### Location of the documentation

https://www.staircase.dev/en/latest/getting_started/intro_tutorials/05_comparing.html#logical

**Note**: You can check the latest versions of the docs on `master` [here](https://www.staircase.dev/en/master/).

#### Documentation problem
Typo below:

To answer the question of “what if the step function is not boolean valued” we appeal to the boolean definition that Python applies to numbers;anything not zero is considered true, and consequently only zero is false.

**Comment by Pavithradevadiga** [comment]
@venaturum I do not see any typo in 

*To answer the question of “what if the step function is not boolean valued” we appeal to the boolean definition that Python applies to numbers;anything not zero is considered true, and consequently only zero is false.*

**Comment by venaturum** [comment]
Hi @Pavithradevadiga , there are no spelling mistakes, just need 
` numbers;anything `
to become
` numbers: anything`

**Comment by Pavithradevadiga** [comment]
@venaturum thanks for clarifying, I have created a pull request #127 to update the same please check
